required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
]

[[constraint]]
  branch = "master"
  name = "github.com/gogo/status"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-gateway"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    non-go = false
